name: 'Setup Webots'
description: 'Installs Webots on the runner'
outputs:
  bashCmd:
    description: "Start of a command line in bash which will run webots on all runners with options suitable for headless execution. This is also put in the RUN_WEBOTS environment variable."
  home:
    description: "Path of the Webots installation, suitable for putting in WEBOTS_HOME environment variable"
  binDir:
    description: "Directory containing the Webots executable, suitable for adding to the PATH environment variable"
  bin:
    description: "Full path to the Webots executable, suitable for running webots directly (albeit probably not succesfully, that's what bashCmd or $RUN_WEBOTS is for)"
runs:
  using: 'composite'
  steps:
    - name: 'Download and Install Webots'
      run: |
        webotsOptions="--no-rendering --stdout --stderr --minimize --batch"
        if [ '${{ runner.os }}' = 'Linux' ]; then
          webotsHome="/snap/webots/current/usr/share/webots"
          webotsBinDir="${webotsHome}"
          webotsBin="${webotsBinDir}/webots"
          webotsBashCmd="xvfb-run -a ${webotsBin} ${webotsOptions}"
        elif [ '${{ runner.os }}' = 'Windows' ]; then
          webotsHome="${LOCALAPPDATA}/Programs/Webots"
          webotsBinDir="${webotsHome}/msys64/mingw64/bin"
          webotsBin="${webotsBinDir}/webots"
          webotsBashCmd="${webotsBin} ${webotsOptions}"
          echo "MESA_GL_VERSION_OVERRIDE=3.3" >> $GITHUB_ENV
          pkgName=webots-R2021a_setup.exe
        elif [ '${{ runner.os }}' = 'macOS' ]; then
          webotsHome="$HOME/Applications/Webots.app"
          webotsBinDir="${webotsHome}"
          webotsBin="${webotsBinDir}/webots"
          webotsBashCmd="${webotsBin} ${webotsOptions}"
          pkgName=webots-R2021a.dmg
        else
          echo "Unrecognized runner OS"
          exit -1
        fi
        echo "RUN_WEBOTS=$webotsBashCmd" >> $GITHUB_ENV
        echo "LIBGL_ALWAYS_SOFTWARE=true" >> $GITHUB_ENV
        echo "WEBOTS_DISABLE_SAVE_SCREEN_PERSPECTIVE_ON_CLOSE=true" >> $GITHUB_ENV
        echo "::set-output name=home::${webotsHome}"
        echo "::set-output name=binDir::${webotsBinDir}"
        echo "::set-output name=bin::${webotsBin}"
        echo "::set-output name=bashCmd::${webotsBashCmd}"
        if [ '${{ runner.os }}' = 'Linux' ]; then
          sudo snap install webots
        elif [ '${{ runner.os }}' = 'Windows' ]; then
          curl -L -O "https://github.com/cyberbotics/webots/releases/download/R2021a/$pkgName"
          ./$pkgName //VERYSILENT //SP- //SUPPRESSMSGBOXES //CURRENTUSER
          curl -L -o Mesa.7z https://downloads.fdossena.com/geth.php?r=mesa64-latest
          7z e -o${LOCALAPPDATA}/Programs/Webots/msys64/mingw64/bin Mesa.7z
        elif [ '${{ runner.os }}' = 'macOS' ]; then
          curl -L -O "https://github.com/cyberbotics/webots/releases/download/R2021a/$pkgName"
          mkdir ~/Mount
          mkdir -p ~/Applications
          hdiutil attach $pkgName -noverify -mountpoint ~/Mount
          cp -R ~/Mount/Webots.app ~/Applications
          hdiutil detach ~/Mount
          rmdir ~/Mount
        fi
      shell: bash
