name: 'Setup Webots'
description: 'Installs Webots on the runner'
runs:
  using: 'composite'
  steps:
    - name: 'Download and Install Webots'
      run: |
        if [ '${{ runner.os }}' = 'Linux' ]; then
          pkgName=webots_2021a_amd64.deb
        elif [ '${{ runner.os }}' = 'Windows' ]; then
          pkgName=webots-R2021a_setup.exe
        elif [ '${{ runner.os }}' = 'macOS' ]; then
          pkgName=webots-R2021a.dmg
        else
          echo "Unrecognized runner OS"
          exit -1
        fi
        curl -L -O "https://github.com/cyberbotics/webots/releases/download/R2021a/$pkgName"
        if [ '${{ runner.os }}' = 'Linux' ]; then
          sudo apt update
          sudo apt install --yes ./webots_2021a_amd64.deb
          echo "RUN_WEBOTS=xvfb-run -a webots" >> $GITHUB_ENV
        elif [ '${{ runner.os }}' = 'Windows' ]; then
          ./$pkgName //VERYSILENT //SP- //SUPPRESSMSGBOXES //CURRENTUSER
          curl -L -o Mesa.7z https://downloads.fdossena.com/geth.php?r=mesa64-latest
          7z e -o${LOCALAPPDATA}/Programs/Webots/msys64/mingw64/bin Mesa.7z
          echo "MESA_GL_VERSION_OVERRIDE=3.3" >> $GITHUB_ENV
          echo "${LOCALAPPDATA}/Programs/Webots/msys64/mingw64/bin" >> $GITHUB_PATH
          echo "RUN_WEBOTS=webots" >> $GITHUB_ENV
        elif [ '${{ runner.os }}' = 'macOS' ]; then
          mkdir ~/Mount
          mkdir -p ~/Applications
          hdiutil attach $pkgName -noverify -mountpoint ~/Mount
          cp -R ~/Mount/Webots.app ~/Applications
          hdiutil detach ~/Mount
          rmdir ~/Mount
          echo "$HOME/Applications/Webots.app" >> $GITHUB_PATH
          echo "RUN_WEBOTS=webots" >> $GITHUB_ENV
        fi
        echo "LIBGL_ALWAYS_SOFTWARE=true" >> $GITHUB_ENV
        echo "WEBOTS_DISABLE_SAVE_SCREEN_PERSPECTIVE_ON_CLOSE=true" >> $GITHUB_ENV
      shell: bash
