name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy: 
      fail-fast: false
      matrix:
        # os: [ ubuntu-latest, macos-lastest, windows-latest ]
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Get Webots home
      id: getWebotsHome
      uses: DeepBlueRobotics/setup-webots@add-using-tar
      with:
        install: false
    
    - name: Cache Webots
      uses: actions/cache@v2
      with:
        path: ${{ steps.getWebotsHome.outputs.home }}
        key: webots-v2021a-install-${{ runner.os }}


    - name: Setup Webots
      id: setupWebots
      uses: DeepBlueRobotics/setup-webots@add-using-tar

    - name: Run Webots
      run: $RUN_WEBOTS --sysinfo
      shell: bash

    - name: Display outputs
      run: |
        echo "RUN_WEBOTS: $RUN_WEBOTS"
        echo "steps.setupWebots.outputs.bashCmd: ${{ steps.setupWebots.outputs.bashCmd }}"
        echo "steps.setupWebots.outputs.home: ${{ steps.setupWebots.outputs.home }}"
        echo "steps.setupWebots.outputs.binDir: ${{ steps.setupWebots.outputs.binDir }}"
        echo "steps.setupWebots.outputs.bin: ${{ steps.setupWebots.outputs.bin }}"
      shell: bash


  release:
    # Only release from the main branch
    if: github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Compute next semantic version
      id: version
      uses: paulhatch/semantic-version@v3.2
      with:
        branch: "main"

    - name: Tag
      run: git tag ${{ steps.version.outputs.version_tag }}
    
    - name: Push
      run: git push origin ${{ steps.version.outputs.version_tag }}

