name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy: 
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-lastest, windows-latest ]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Setup Webots
      uses: actions/setup-webots@main
