name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        webotsVersion: [ R2023b, R2024a ]
        webotsTag: [ nightly_26_7_2024, '' ]
        webotsBaseUrl: [ 'https://github.com/DeepBlueRobotics/webots/releases/download/R2024a_DeepBlueSim_2024_07_28', '' ]
        exclude:
          - webotsVersion: R2024a
            webotsTag: nightly_26_7_2024
            os: windows-latest
          - webotsVersion: R2023b
            webotsTag: nightly_26_7_2024
          - webotsVersion: R2023b
            webotsBaseUrl: https://github.com/DeepBlueRobotics/webots/releases/download/R2024a_DeepBlueSim_2024_07_28
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout source
      uses: actions/checkout@v3

    - name: Setup Webots
      id: setupWebots
      uses: ./
      with:
        webotsVersion: ${{ matrix.webotsVersion }}
        webotsTag: ${{ matrix.webotsTag || '' }}

    - name: Run Webots
      run: $RUN_WEBOTS --sysinfo
      shell: bash

    - name: Display outputs
      run: |
        echo "RUN_WEBOTS: $RUN_WEBOTS"
        echo "steps.setupWebots.outputs.bashCmd: ${{ steps.setupWebots.outputs.bashCmd }}"
        echo "steps.setupWebots.outputs.home: ${{ steps.setupWebots.outputs.home }}"
        echo "steps.setupWebots.outputs.binDir: ${{ steps.setupWebots.outputs.binDir }}"
        echo "steps.setupWebots.outputs.bin: ${{ steps.setupWebots.outputs.bin }}"
        echo "steps.setupWebots.outputs.cachePath: ${{ steps.setupWebots.outputs.cachePath }}"
      shell: bash

  release:
    # Only release from the main branch
    if: github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Compute next semantic version
      id: version
      uses: paulhatch/semantic-version@v3.2
      with:
        branch: "main"

    - name: Tag
      run: git tag ${{ steps.version.outputs.version_tag }}

    - name: Push
      run: git push origin ${{ steps.version.outputs.version_tag }}
